### PR TITLE
Graphics

### PR DESCRIPTION
**Pull request by arunsug**
added inheritance to gamestate objects.
implemented scene graph.
still some bugs in transformation for carryign objects.

### CODE REVIEW

**Review by shabbyowen — APPROVED** [review]
Successfully build and run.
Thanks for the work. 
The animations for cats, zombies and water tap are working.

**Review by alzhu1 — APPROVED** [review]

**Review by jbhesania — APPROVED** [review]
works locally

**Review by mis046 — APPROVED** [review]
Runs and nice cats

**Review by EtsuN — APPROVED** [review]
yay

**Pull request merged**
