### PR TITLE
Graphics

### PR DESCRIPTION
**Pull request by arunsug**
Intergration of graphics and network code. We get the game state and render based of that. Run the server and the client and it should render a rabbit the moves of the screen in jumps

### CODE REVIEW

**Review by mis046 — APPROVED** [review]
Successfully built and ran

**Comment by shabbyowen** [comment]
Build and run successfully.

**Review by shabbyowen — APPROVED** [review]

**Review by alzhu1 — APPROVED** [review]
Code runs successfully on cloudlabs!

**Comment by EtsuN** [comment]
Hello

**Review by EtsuN — APPROVED** [review]
perfecto

**Pull request merged**
