### PR TITLE
Added config reader for GameState

### PR DESCRIPTION
**Pull request by alzhu1**
Initial config using INI config files is implemented: try playing around with it. You should be able to modify stuff like the number of tools, the properties of the seed shack/water tap, and the size/type of the tiles (you should be able to set the path of the zombies this way too).

There's room for other additions to the INI file format, just depends on what we want to be able to configure.

One thing I noticed when testing was that when the zombie goes left and reaches a tile where they go down, they appear to be one tile too early. Picture below as an example.

Screen Shot 2020-05-06 at 11 42 12 PM

### CODE REVIEW

**Comment by alzhu1** [comment]
Oh, I just realized:

So I forgot to test changing the number of tools, but I think that might result in some weird behavior. Right now in `NetworkClient`, we're initializing a dummy `GameState` that's used before receiving an actual `GameState` message from the server. I think we should move away from this, because this dummy GameState assumes only 2 tools are there, and assigns object IDs to them. However, if the config's number of tools change (say from 2 to 3), then this will result in an ID mismatch between the dummy `GameState` and the server's `GameState`.

(e.g. dummy state might give the tools the IDs 100 and 101, then the seed shack ID 102. But if there are 3 tools in the config, then the server gives the tools IDs 100, 101, and 102. That means 102 matches to a `Tool` on the server's state, and matches to a `SeedShack` in the client's dummy state)

Again, haven't tested this, but if some weird stuff does happen when changing the number of tools, then I would guess it's because of the client's dummy state. We should get rid of it anyway since the server is the single source of truth, and we want to use `GameStates` only from the server.

**Comment by EtsuN** [comment]
Alex, could you try to remove the tile creation code in the default block in the switch statement and move it to "*"'s case block; maybe it is creating an extra tile for each "\n".
Also, I couldn't see the changes being reflected, maybe I'm doing something wrong or maybe due to the dummy gameState Alex mentioned.
And thx for the works, the ini file looks cool and smart^^

**Comment by alzhu1** [comment]
Oh, for the changes not being reflected, if you're running the server code from powershell, you have to be in the game_server directory. (So you can execute it like "../Debug/game_server.exe")

It's because the INI file is in game_server, but the executable is in Debug, so the working directory doesn't contain the config file if you're in Debug. This also would work if you run the server code in Visual Stuio.

If either is not the case, then that's weird; could you provide more context? I'll look into it more. And I'll try removing the default block and see if that changes anything.

**Comment by alzhu1** [comment]
For the zombies moving down one tile earlier than they should, removing the default condition didn't change it. I don't think there are any newline characters, I think `std::getline` strips them off the string.

If I had to guess, it might be related to our zombie moving code, specifically calculating the "current tile" of the zombie. We can try looking into that?

**Comment by alzhu1** [comment]
Wrote something quickly to only start rendering game state if it's been initialized, so when client boots up it should look empty for a short time, then render the game.

**Comment by EtsuN** [comment]
The bug should be fixed as shown in the attached screenshots. The cause was that we always subtracted the tile padding regardless of the direction. The padding for x,y should be applied based on the current direction so that we could compute the correct row/column of the corresponding tile.
However, really trivial but there's a bit of offset in the zombie's position after having its direction changed multiple times because we do not snap their position to the center of the tile. But since it shouldn't be a major issue considering we are having a relatively simple path, we can leave as it is for now.

スクリーンショット (27)
スクリーンショット (28)

**Review by EtsuN — APPROVED** [review]
Forgot to approve

**Review by shabbyowen — APPROVED** [review]
Thanks Alex for the great work!
Can't wait to move everything in config files

**Review by mis046 — APPROVED** [review]
Works great!

**Review by jbhesania — APPROVED** [review]

**Review by arunsug — APPROVED** [review]

**Pull request merged**
