### PR TITLE
Planting stage done

### PR DESCRIPTION
**Pull request by shabbyowen**
The growing stage progress is implemented.
Graphics can use following members to render plant model & growing progress bar
```
static enum class PlantType { CORN = 0, PEA_SHOOTER = 1 };
static enum class GrowStage { SEED = 0, SAPLING = 1, BABY = 2, GROWN = 3 };

PlantType plantType;
GrowStage growStage;
float growExpireTime;     // Time(s) need to grow in current stage
float growProgressTime;   // Time(s) of current grow stage
```

Please make sure the following is working before accept the request:
1. Pick up a water can by pressing `space`
2. Press `E` while holding the water can, you should see info about the distance to the nearest plant (currently only a dummy corn is at (5, 5))
3. Walk within the range of collision (distance < 2) and press `E` it will start watering the plant (progress will be printed)
4. When the plant is `GROWN` the growing progress will no longer increase.

### CODE REVIEW

**Review by EtsuN — APPROVED** [review]
Works!

**Review by mis046 — APPROVED** [review]
Nice!

**Review by arunsug — COMMENTED** [review]
Works great!

**Review by arunsug — APPROVED** [review]

**Review by alzhu1 — APPROVED** [review]
Works great, thanks!

**Pull request merged**
