### PR TITLE
Graphics

### PR DESCRIPTION
**Pull request by mis046**
1. Added progress bar for the cool down
2. Added bug animations and spray model

### CODE REVIEW

**Review by shabbyowen — APPROVED** [review]
Beautiful!

**Review by alzhu1 — APPROVED** [review]
It looks super good, nice!

**Review by arunsug — APPROVED** [review]
👍

**Review by EtsuN — APPROVED** [review]
good

**Review by jbhesania — APPROVED** [review]
Great! makes watering way better

**Pull request merged**
