### PR TITLE
Gameplay week8

### PR DESCRIPTION
**Pull request by shabbyowen**
Please play around with highlighting & collision with zombie.
The player should not be able to move out of boundaries
We have an invincible time when you collide with zombie during which your position is frozen when collide with zombie again.

### CODE REVIEW

**Review by EtsuN — APPROVED** [review]
The tile highlighting looks awesome!
For the third one, I'm not sure what is expected but the player bounces back the first time, and freezes the second time when it contacts the zombie.

**Review by mis046 — APPROVED** [review]
Nice!

**Comment by alzhu1** [comment]
> For the third one, I'm not sure what is expected but the player bounces back the first time, and freezes the second time when it contacts the zombie.

@EtsuN The "invincible time" is supposed to prevent players from taking damage and getting knocked back, but we still want the zombies to act like walls (i.e. can't move through a zombie). We can change the behavior depending on how weird/wonky it might be.

**Review by alzhu1 — APPROVED** [review]
Tile highlighting and collisions are working, but the seed bag is being highlighted a bit strangely. In the picture I'm facing a seed bag, but a different one is highlighted. Double checked the object highlight ID and they're changing correctly, the ID is set to the bag I'm facing. 

I think it's related to the `bool highlight` being in `Drawable`. All the seed bag nodes share the same `AssimpModel` so if a seed bag should be highlighted, I think the first seed bag node that gets drawn is highlighted. But the first seed bag isn't always the same seed bag that the player is facing. Would it work if the `bool highlighted` was a member variable of `SceneNode` instead and it gets passed to `obj->draw`? That way the highlight is set for each individual node (tool).

@arunsug @EtsuN @mis046

Screen Shot 2020-05-20 at 12 31 09 AM

**Comment by EtsuN** [comment]
> Tile highlighting and collisions are working, but the seed bag is being highlighted a bit strangely. In the picture I'm facing a seed bag, but a different one is highlighted. Double checked the object highlight ID and they're changing correctly, the ID is set to the bag I'm facing.
> 
> I think it's related to the `bool highlight` being in `Drawable`. All the seed bag nodes share the same `AssimpModel` so if a seed bag should be highlighted, I think the first seed bag node that gets drawn is highlighted. But the first seed bag isn't always the same seed bag that the player is facing. Would it work if the `bool highlighted` was a member variable of `SceneNode` instead and it gets passed to `obj->draw`? That way the highlight is set for each individual node (tool).
> 
> @arunsug @EtsuN @mis046
> 
> Screen Shot 2020-05-20 at 12 31 09 AM

I'm not sure about the highlighting logic, but having the highlight attribute in the scene node sounds like right

**Review by arunsug — APPROVED** [review]
The highlighting looks great mostly. Theres a small issue with the wrong seedbag getting highlighted but I posted about that in the slack. Its a small issue so I'll just approve this now. Also the collisions of the zombie and player are kind of odd when you just keep walking into them but I'm not sure if it's a problem

**Review by jbhesania — APPROVED** [review]
image
The freezing looks like it works like planned. Just a general concern is that the seed shack isnt on a single tile or completely on multiple tiles so you can do things like the above. Small thing to maybe fix by changing the position of seed shack and making sure we can't plant on tiles affected.

**Pull request merged**
