### PR TITLE
Network integrated with graphics

### PR DESCRIPTION
**Pull request by shabbyowen**
**Major things we changed in `Client` class:**

1. Add two instance variables `NetworkClient* netClient` and `GameState* currentGameState`
2. The `Client::loop()` function:
     Now for each iteration, `NetworkClient` will provide the latest `GameState` and assign to `currentGameState` and graphics team can update graphics based on everything in `currentGameState`

**Misc:**
1. All header `.hpp` files from `shared_game_object` are now in `include` folder. Both client and server need them.
2. We probably won't need `sendEvents()` and `recieveState()` because events are sent everywhere asynchronously (for example key press) and all receive operations will be on a different thread and `NetworkClient` takes care of that
3. The design of `GameState` is not finalized so we need to discuss about this next.
4. The format of event message sending to server is not finalized. Temporary dummy ones are just `string`
5. Current dummy update in server side is for each tick add 1 to  `x`,`y`,`z` of each `Player`'s `Position`

Please confirm following things work before accept the request:

1. Run server using command: `.\game_server.exe 13 <tickrate>`
2. Then run the game_client via Visual Studio debugger.
3. You should be able to see keyboard press messages (in console output of both client and server) sent from client to server

After merge, `network` branch and `shared_game-object` branch will be deleted.

### CODE REVIEW

**Review by arunsug — APPROVED** [review]
It looks good to me. I'd like to make some changes to the game objects but they're small adjustments we can make later.

**Review by mis046 — APPROVED** [review]
Looking good!

**Comment by EtsuN** [comment]
I need 20hr more to download boost, so I'll just approve it for now

**Review by EtsuN — APPROVED** [review]
I need 20hr more to download boost, so I'll just approve it for now

**Review by jbhesania — APPROVED** [review]

**Review by alzhu1 — APPROVED** [review]
Works on cloud desktop!

**Pull request merged**
