### PR TITLE
Gameplay week8

### PR DESCRIPTION
**Pull request by shabbyowen**
Things to check:
1. Zombies are coming in waves, every wave there will be increasing difficulty (more hp and more amount of zombies)
2. Naive implementation of collision response between players and all game objects except tools and plants (Still has bugs when planting the seeds so I disable it for plants)
3. One-time plowing: The progress of plowing will reset if player stop plowing

After Merging:
1. Graphics integration of new plant and attack - Cactus and CactusBullet
2. 

Bug fix:
1. Fix wrong highlighted tiles when facing left & up
2. Fix allow interaction with tiles where SeedShacks &  WaterTap

### CODE REVIEW

**Review by EtsuN — APPROVED** [review]
thanks guys for all the works; looks good; few things need to be fix on the graphics side

Bug fix to-be-done on graphics:
1. Flashing rabbit animation (probably dueu to overlapping end frame of walk anim and start frame of die anim)
2. Tools and seed shack are positioned on the grid vertices instead of inside the grids
3. The flashing effect of the health bar for rabbits looks bad; can be solved by slowing the bar shrinking speed or add extra render times before & after the bar update

**Comment by shabbyowen** [comment]
> 2. Tools and seed shack are positioned on the grid vertices instead of inside the grids

Can this can be fixed by change the positions of seed shack `initGameState.ini`?

**Comment by EtsuN** [comment]
> > 1. Tools and seed shack are positioned on the grid vertices instead of inside the grids
> 
> Can this can be fixed by change the positions of seed shack `initGameState.ini`?

I think the ini is the position based on the grid but not based on the world axis, so should be fixed in the code??

**Comment by EtsuN** [comment]
The seed shack is actually not at the grid vertice but the grid side:
|‾‾‾‾‾‾|‾‾‾‾‾‾|
|ooooxoooo|
|______|______y

x is where the seed shack is at, y is where the tool is at, (o is just space)

**Comment by alzhu1** [comment]
> The seed shack is actually not at the grid vertice but the grid side:
> |‾‾‾‾‾‾|‾‾‾‾‾‾|
> |ooooxoooo|
> |______|______y
> 
> x is where the seed shack is at, y is where the tool is at, (o is just space)

It looks like adding 0.5 to the SeedShack's x position will place it directly on the tile (e.g. if position is (6.5, 0, 6), it will be on tile (6, 6)). Not quite sure why it's offset by about 0.5 in the horizontal direction, but not in the z direction. Does the model need to be centered?

**Review by alzhu1 — APPROVED** [review]
Thanks for fixing the tile highlighting bug when facing left and up; it's looking good!

**Comment by EtsuN** [comment]
> It looks like adding 0.5 to the SeedShack's x position will place it directly on the tile (e.g. if position is (6.5, 0, 6), it will be on tile (6, 6)). Not quite sure why it's offset by about 0.5 in the horizontal direction, but not in the z direction. Does the model need to be centered?

The collision looks weird when it is off from the center of the tile; but it should be a easy fix on the client side

**Review by mis046 — APPROVED** [review]

**Review by arunsug — APPROVED** [review]
Nice

**Review by jbhesania — APPROVED** [review]
Great!
Small note: even when this is merged with master, you cannot see the cactuses, so just a heads up that we need to fix something there (likely on graphics end?)

**Pull request merged**
