### PR TITLE
Graphics ui

### PR DESCRIPTION
**Pull request by arunsug**
Hey guys, there a few major package changes so I wanted to double check that it works for you guys before I merge it.

In order to make sure it works:
When you run the client the first page should just be a textbox with the defualt value set to "localhost" and a button. 
Make sure you can edit the textbox.
If you run the server on you computer you can just hit enter with "localhost" in the textbox and you should enter the game as normal.
Make sure everything renders correctly and nothing looks different.
If you can run a remote server try typing in that IP address and connecting. I wasn't able to test that but it shouldn't be an issue so no worries. 

We switch from glew to glad witch changes some things but not much.
We include nanogui and all of its packages
Using nanogui causes some issues with settings that affect the rendering but I think I've resolved them.

### CODE REVIEW

**Review by mis046 — APPROVED** [review]
Nice works perfectly good job!

**Review by shabbyowen — APPROVED** [review]
Great job! The remote IP works for me.
One issue is that it seems you can change the camera view angle before you enter the lobby.
I guess in the final release we can fix the camera angle and disable mouse to change camera angle

**Comment by alzhu1** [comment]
Having a bit of trouble getting it to work on cloudlabs, it's complaining about `ft2build.h` not being found. I'm guessing Freetype isn't installed on the machine, so I'll try downloading it manually. Did everyone else already have Freetype installed/did you encounter a problem saying `ft2build.h not found`?

**Review by alzhu1 — APPROVED** [review]
Got it working, and it works great! Super awesome that we can specify the ip address now.

**Review by EtsuN — APPROVED** [review]
soooooo coooooooool!! thx arun

**Pull request merged**
