### PR TITLE
Zombie spawn; Picking up tools; Player movement control

### PR DESCRIPTION
**Pull request by shabbyowen**
Following features are implemented. Please check before accept:
- Zombie spawn every 1s and will disappear when it reaches end in U-shaped map
- Player moved in 8 direction and can rotate when switch direction.
- Press space to pick up a nearest tool and model will hold it.

### CODE REVIEW

**Review by EtsuN — APPROVED** [review]
Sooo cooooooooool

**Review by mis046 — APPROVED** [review]
Perfect!

**Review by arunsug — APPROVED** [review]
Works great!

**Review by alzhu1 — APPROVED** [review]
Tested and works on cloudlabs

**Review by jbhesania — APPROVED** [review]

**Pull request merged**
