### PR TITLE
Gameplay week7

### PR DESCRIPTION
**Pull request by shabbyowen**
Check HomeBase hp
Check highlighting game objects (See console outputs)

Now the server can be run without arguments because network configurations are moved to `ServerConfig.ini`

### CODE REVIEW

**Review by EtsuN — APPROVED** [review]
Perfecto

**Review by arunsug — APPROVED** [review]
Noice.

**Review by mis046 — APPROVED** [review]
Great

**Review by jbhesania — APPROVED** [review]

**Review by alzhu1 — APPROVED** [review]
Works

**Pull request merged**
