### PR TITLE
Graphics

### PR DESCRIPTION
**Pull request by arunsug**
See player hp bar see it go down disappear whne the player dies and reappear when regrown
See the score increase whenever a zombie is killed. 
Make sure the plant attack speed double with every fertilizer use then go back to normal after a bit.
fertilizer model should be better.
Particle speed slower. (whne corn attacks and watertap)
doesn't crash when closed.
Player modle is smaller and in the config

### CODE REVIEW

**Comment by EtsuN** [comment]
thx for the works orzzzz

**Review by mis046 — APPROVED** [review]
Nice

**Review by shabbyowen — APPROVED** [review]
Cool!

**Review by alzhu1 — APPROVED** [review]
good stuff

**Pull request merged**
