### PR TITLE
Graphics

### PR DESCRIPTION
**Pull request by mis046**
1. Player animations
2. 3 more player models
3. UI has been added
4. Zombie dying animations
5. Corn attack interval

### CODE REVIEW

**Review by arunsug — APPROVED** [review]
👍 🥇 💯

**Review by EtsuN — APPROVED** [review]
( ﾟДﾟ)

**Review by shabbyowen — APPROVED** [review]
So COOOOOOOL

**Review by alzhu1 — APPROVED** [review]
The animations are super cool, nice!

**Pull request merged**
