### PR TITLE
Gameplay week9

### PR DESCRIPTION
**Pull request by shabbyowen**
Merge and we will have play testing during today's meeting
* handle player death (player becomes seedbags)
* Player spawn at different positions
More stuff to check...

### CODE REVIEW

**Review by mis046 — COMMENTED** [review]
There's an issue that my player just freezes after running into zombies for several times. Can't move at all.

**Comment by alzhu1** [comment]
That should be the player "dying"; a seed bag should appear where the player is when you can't move anymore. Another player should be able to pick up the seed bag and plant/grow it, then the player should appear there.

To test this, I think you could start up a second client instance to add a second player, then plant the first player's seed bag.

We include a `isDead` field as part of the `Player`; if `isDead` is true, then we don't want to render the player.

**Review by mis046 — APPROVED** [review]
Nice

**Review by arunsug — APPROVED** [review]
Works for me

**Review by alzhu1 — APPROVED** [review]

**Review by jbhesania — APPROVED** [review]

**Pull request merged**
