### PR TITLE
Graphics seedchat

### PR DESCRIPTION
**Pull request by EtsuN**
DOES NOT BREAK BY FMOD
The secret cat is secret now
Player seed/plant can chat now

Please do not merge yet since I am still slightly adjusting some of the tool's angle; I will merge it later

### CODE REVIEW

**Review by mis046 — APPROVED** [review]
I trust you

**Comment by shabbyowen** [comment]
Final Merge :(

**Review by arunsug — APPROVED** [review]
Noice

**Review by shabbyowen — APPROVED** [review]
Final Merge :(

**Review by alzhu1 — COMMENTED** [review]
11/10

**Pull request merged**
