### PR TITLE
Project structure

### PR DESCRIPTION
**Pull request by shabbyowen**
If you can successfully build what we currently have (graphics_client and network client/server), then please approve this pull request

### CODE REVIEW

**Review by EtsuN — APPROVED** [review]
build all success

**Review by alzhu1 — APPROVED** [review]
Thanks for setting up the libraries! I got the graphics-basic and network/init_test code to work with this project structure. I ran this on the cloud desktop, and had a few problems with the graphics example that I'll just list fixes here for reference:

* the "const char[] to char*" conversion error was because conformance mode was turned on, apparently it's been a thing since VS2017. you can disable it by going to the Project Properties -> C/C++ -> Language and removing the "Yes (/permissive-)" option

* had another error about strncpy being unsafe, for now a fix was to add "CRT_SECURE_NO_WARNINGS" in Project Properties -> C/C++ -> Preprocessor -> Preprocessor Definitions

* The source code in Core.h of the graphics-basic branch tries to load the glew.lib library (on line 16), but the library we have is called glew32.lib. changing the name of it in Core.h worked

**Comment by alzhu1** [comment]
Since they would be common errors, added a commit to fix the first 2 bullet points from earlier. The 3rd point should be kept in mind when pushing graphics-client related code (i.e. edit Core.h)

**Review by arunsug — APPROVED** [review]
Works for to me. Thank for listing those errors Alex. 

- For the const char error it really should be const, it was unsafe that it wasn't so I changed the references to in my code. You can flip that setting back if you'd like.
- For the strncpy error I'm also going to remove the line and probably that whole class in the future so unless other people want to use strncpy its fine if we have to use a different function.

**Review by mis046 — APPROVED** [review]
Built successfully. Thanks for the work!

**Review by jbhesania — APPROVED** [review]
Except for adding alex's changes to configurations to x32, this looks great! thanks

**Pull request merged**
